#events.py
# Structured event payloads for TravelFacade's publisher side. The older
# landmark/halfway/finished events just pass a ready-to-print string
# (ConsoleAlertListener.update() prints it as-is) - a listener that has to
# build its own message (EmailAlertsListener) needs the pieces, not a
# pre-formatted sentence, so "checkpoint_reached" carries this instead.

from dataclasses import dataclass
import uuid


@dataclass(frozen=True)
class CheckpointReachedEvent:
    user_id: uuid.UUID
    user_name: str  # User has no separate display-name field yet - callers pass its email
    checkpoint_name: str
    checkpoint_number: int
    description: str  # already generated by travel_logic/checkpoints.py's generate_description()
