"""add checkpoint generation progress tracking

Revision ID: 871536f8b346
Revises: 0f95228a5f6a
Create Date: 2026-09-28 16:49:35.444347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '871536f8b346'
down_revision: Union[str, Sequence[str], None] = '0f95228a5f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('active_trips', sa.Column('checkpoints_ready_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('trip_checkpoints', sa.Column('description_status', sa.String(), server_default='pending', nullable=False))
    op.create_check_constraint(
        'ck_trip_checkpoints_description_status', 'trip_checkpoints', "description_status IN ('pending', 'ready')"
    )
    # Every checkpoint written before this migration was created the old
    # way - the full synchronous pipeline, description already filled in -
    # so it's really "ready", not the column's new-row default of
    # "pending" (which would otherwise wrongly show existing checkpoints
    # as still generating). Likewise, every trip that already exists
    # necessarily has its (possibly empty) checkpoint list already
    # complete - there's no background job left to finish for it.
    op.execute("UPDATE trip_checkpoints SET description_status = 'ready' WHERE description <> ''")
    op.execute("UPDATE active_trips SET checkpoints_ready_at = now() WHERE checkpoints_ready_at IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_trip_checkpoints_description_status', 'trip_checkpoints', type_='check')
    op.drop_column('trip_checkpoints', 'description_status')
    op.drop_column('active_trips', 'checkpoints_ready_at')
    # ### end Alembic commands ###
