"""create active_trips and trip_checkpoints

Revision ID: 92ff7381ebca
Revises: 2dc7ee53c5e7
Create Date: 2026-09-21 15:44:12.415413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92ff7381ebca'
down_revision: Union[str, Sequence[str], None] = '2dc7ee53c5e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_trips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('from_place', sa.String(), nullable=False),
    sa.Column('to_place', sa.String(), nullable=False),
    sa.Column('start_lat', sa.Float(), nullable=False),
    sa.Column('start_lng', sa.Float(), nullable=False),
    sa.Column('end_lat', sa.Float(), nullable=False),
    sa.Column('end_lng', sa.Float(), nullable=False),
    sa.Column('route_geometry', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('total_distance_m', sa.Float(), nullable=False),
    sa.Column('meters_walked', sa.Float(), server_default='0', nullable=False),
    sa.Column('stride_length_m', sa.Float(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('stride_by_type', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('workout_intervals', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('milestones_notified', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('round_trip', sa.Boolean(), nullable=False),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_paused_seconds', sa.Float(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'paused', 'completed', 'abandoned')", name='ck_active_trips_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_checkpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('checkpoint_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('distance_from_start_m', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('hit_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['active_trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_checkpoints')
    op.drop_table('active_trips')
    # ### end Alembic commands ###
